<?php

/**
 * This is the model base class for the table "tbl_feedback_question".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FeedbackQuestion".
 *
 * Columns in table "tbl_feedback_question" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $question_content
 * @property string $question_answer
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $question_type
 * @property integer $status
 *
 */
abstract class BaseFeedbackQuestion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_feedback_question';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FeedbackQuestion|FeedbackQuestions', $n);
	}

	public static function representingColumn() {
		return 'question_content';
	}

	public function rules() {
		return array(
			array('created_at, updated_at, question_type, status', 'numerical', 'integerOnly'=>true),
			array('question_content, question_answer', 'safe'),
			array('question_content, question_answer, created_at, updated_at, question_type, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, question_content, question_answer, created_at, updated_at, question_type, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'question_content' => Yii::t('app', 'Question Content'),
			'question_answer' => Yii::t('app', 'Question Answer'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'question_type' => Yii::t('app', 'Question Type'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('question_content', $this->question_content, true);
		$criteria->compare('question_answer', $this->question_answer, true);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);
		$criteria->compare('question_type', $this->question_type);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}