<?php

/**
 * This is the model base class for the table "tbl_feedback".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Feedback".
 *
 * Columns in table "tbl_feedback" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $feedback_id
 * @property string $feedback_content
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $type
 * @property integer $event_id
 *
 */
abstract class BaseFeedback extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_feedback';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Feedback|Feedbacks', $n);
	}

	public static function representingColumn() {
		return 'feedback_content';
	}

	public function rules() {
		return array(
			array('created_at, updated_at, type, event_id', 'numerical', 'integerOnly'=>true),
			array('feedback_content', 'safe'),
			array('feedback_content, created_at, updated_at, type, event_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('feedback_id, feedback_content, created_at, updated_at, type, event_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'feedback_id' => Yii::t('app', 'Feedback'),
			'feedback_content' => Yii::t('app', 'Feedback Content'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'type' => Yii::t('app', 'Type'),
			'event_id' => Yii::t('app', 'Event'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('feedback_id', $this->feedback_id);
		$criteria->compare('feedback_content', $this->feedback_content, true);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);
		$criteria->compare('type', $this->type);
		$criteria->compare('event_id', $this->event_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}