<?php

/**
 * This is the model base class for the table "tbl_feedback_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FeedbackUser".
 *
 * Columns in table "tbl_feedback_user" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $question_id
 * @property integer $point
 * @property string $answer
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $status
 *
 */
abstract class BaseFeedbackUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_feedback_user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FeedbackUser|FeedbackUsers', $n);
	}

	public static function representingColumn() {
		return 'answer';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('id, question_id, point, created_at, updated_at, status', 'numerical', 'integerOnly'=>true),
			array('answer', 'safe'),
			array('question_id, point, answer, created_at, updated_at, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, question_id, point, answer, created_at, updated_at, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'question_id' => Yii::t('app', 'Question'),
			'point' => Yii::t('app', 'Point'),
			'answer' => Yii::t('app', 'Answer'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('question_id', $this->question_id);
		$criteria->compare('point', $this->point);
		$criteria->compare('answer', $this->answer, true);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}